#!/bin/sh
# MIT License
# Copyright (c) 2018 Lenic <Lenic@live.cn>

set -e

main () {
  if [ ! -f "/data/tiddlywiki.info" ]; then
    tiddlywiki /data --init server
  fi

  tiddlywiki /data --server \
    "$TW_PORT" \
    "$TW_ROOTTIDDLER" \
    "$TW_RENDERTYPE" \
    "$TW_SERVETYPE" \
    "$TW_USERNAME" \
    "$TW_PASSWORD" \
    "$TW_HOST" \
    "$TW_PATHPREFIX"
}

main "$@"
